import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Providers from "../lib/Providers";
import { Flex } from "@chakra-ui/react";
import { Header } from "@/components/header";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GableURL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Providers>
          <Flex minH="100vh" flexDir="column">
            <Header />
            {children}
          </Flex>
        </Providers>
      </body>
    </html>
  );
}
